import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { AssignPlanDto, CreateNodeDto, MoveBotDto, SavePlanDto, UpdateNodeDto, UpdateUserDto, UserLimitsDto } from './admin.dto';

@Injectable()
export class AdminService {
  constructor(private readonly prisma: PrismaService) {}
  async overview() {
    const [users,bots,nodes,running,suspended]=await Promise.all([this.prisma.user.count(),this.prisma.bot.count(),this.prisma.executionNode.count(),this.prisma.bot.count({where:{status:'RUNNING'}}),this.prisma.user.count({where:{status:'SUSPENDED'}})]);
    return { users,bots,nodes,running,suspended };
  }
  users(){return this.prisma.user.findMany({select:{id:true,email:true,displayName:true,role:true,status:true,lastLoginAt:true,createdAt:true,_count:{select:{bots:true}}},orderBy:{createdAt:'desc'}})}
  async updateUser(actorId:string,id:string,input:UpdateUserDto){
    if(actorId===id&&(input.role!=='ADMIN'||input.status!=='ACTIVE'))throw new BadRequestException('Você não pode remover ou suspender seu próprio acesso administrativo');
    return this.prisma.user.update({where:{id},data:{role:input.role,status:input.status},select:{id:true,email:true,displayName:true,role:true,status:true}}).catch(()=>{throw new NotFoundException('Usuário não encontrado')});
  }
  async userDetail(id:string){const user=await this.prisma.user.findUnique({where:{id},select:{id:true,email:true,displayName:true,role:true,status:true,createdAt:true,lastLoginAt:true,planId:true,plan:{include:{limits:{where:{scope:'PLAN'},take:1}}},bots:{include:{runtime:true,node:{select:{id:true,name:true}},trafficPeriods:{where:{periodStart:{gte:this.monthStart()}},take:1}},orderBy:{createdAt:'desc'}},limits:{where:{scope:'USER'},take:1}}});if(!user)throw new NotFoundException('Usuário não encontrado');const effective=user.limits[0]||user.plan?.limits[0]||await this.defaultLimit();const usage={cpuMillicores:Math.round(user.bots.reduce((n,b)=>n+(b.cpuUsagePercent||0)*10,0)),memoryMb:user.bots.reduce((n,b)=>n+b.memoryUsageMb,0),diskMb:user.bots.reduce((n,b)=>n+b.diskUsageMb,0),trafficMb:user.bots.reduce((n,b)=>n+Number((b.trafficPeriods[0]?.ingressBytes||0n)+(b.trafficPeriods[0]?.egressBytes||0n))/1048576,0),bots:user.bots.length};return{...user,limits:user.limits.map(x=>this.serializeLimit(x)),effectiveLimits:this.serializeLimit(effective),usage}}
  async saveUserLimits(userId:string,input:UserLimitsDto){if(!await this.prisma.user.count({where:{id:userId}}))throw new NotFoundException('Usuário não encontrado');this.validateLimitInput(input);await this.assertUserReservations(userId,input);const existing=await this.prisma.resourceLimit.findFirst({where:{scope:'USER',userId}});const data=this.limitData(input,{scope:'USER' as const,userId});const limit=existing?await this.prisma.resourceLimit.update({where:{id:existing.id},data}):await this.prisma.resourceLimit.create({data});return this.serializeLimit(limit)}
  async plans(){const plans=await this.prisma.resourcePlan.findMany({include:{limits:{where:{scope:'PLAN'},take:1},_count:{select:{users:true}}},orderBy:[{isDefault:'desc'},{name:'asc'}]});return plans.map(p=>({...p,limits:p.limits.map(x=>this.serializeLimit(x))}))}
  async savePlan(id:string|undefined,input:SavePlanDto){this.validateLimitInput(input);return this.prisma.$transaction(async tx=>{if(input.isDefault)await tx.resourcePlan.updateMany({data:{isDefault:false}});const plan=id?await tx.resourcePlan.update({where:{id},data:{name:input.name.trim(),description:input.description?.trim()||null,isDefault:input.isDefault,enabled:input.enabled}}):await tx.resourcePlan.create({data:{name:input.name.trim(),description:input.description?.trim()||null,isDefault:input.isDefault,enabled:input.enabled}});const existing=await tx.resourceLimit.findFirst({where:{scope:'PLAN',planId:plan.id}});const data=this.limitData(input,{scope:'PLAN' as const,planId:plan.id});const limit=existing?await tx.resourceLimit.update({where:{id:existing.id},data}):await tx.resourceLimit.create({data});return{...plan,limits:[this.serializeLimit(limit)]}})}
  async assignPlan(userId:string,input:AssignPlanDto){if(input.planId&&!await this.prisma.resourcePlan.count({where:{id:input.planId,enabled:true}}))throw new BadRequestException('Plano inválido ou desativado');return this.prisma.user.update({where:{id:userId},data:{planId:input.planId||null},select:{id:true,planId:true}}).catch(()=>{throw new NotFoundException('Usuário não encontrado')})}
  async nodes(){const nodes=await this.prisma.executionNode.findMany({include:{_count:{select:{bots:true}}},orderBy:{createdAt:'desc'}});return nodes.map(({agentTokenHash,...node})=>({...node,status:node.lastHeartbeatAt&&Date.now()-node.lastHeartbeatAt.getTime()>90000?'OFFLINE':node.status,totalDiskMb:node.totalDiskMb.toString()}))}
  async createNode(input:CreateNodeDto){
    const token=randomBytes(32).toString('base64url'); const tokenHash=createHash('sha256').update(token).digest('hex');
    const node=await this.prisma.executionNode.create({data:{name:input.name.trim(),hostname:'Aguardando conexão',enrollments:{create:{tokenHash,expiresAt:new Date(Date.now()+15*60*1000)}}}});
    const {agentTokenHash,...safeNode}=node;
    return {...safeNode,totalDiskMb:node.totalDiskMb.toString(),enrollmentToken:token,expiresInSeconds:900};
  }
  async updateNode(id:string,input:UpdateNodeDto){const node=await this.prisma.executionNode.update({where:{id},data:{status:input.status}}).catch(()=>{throw new NotFoundException('Servidor não encontrado')});const{agentTokenHash,...safeNode}=node;return{...safeNode,totalDiskMb:node.totalDiskMb.toString()}}
  async deleteNode(id:string){const count=await this.prisma.bot.count({where:{nodeId:id}});if(count)throw new ConflictException(`Migre os ${count} bot(s) antes de remover este servidor`);await this.prisma.executionNode.delete({where:{id}}).catch(()=>{throw new NotFoundException('Servidor não encontrado')});return{success:true}}
  bots(){return this.prisma.bot.findMany({include:{user:{select:{displayName:true,email:true}},runtime:true,node:{select:{id:true,name:true,status:true}}},orderBy:{createdAt:'desc'}})}
  async moveBot(id:string,input:MoveBotDto){const bot=await this.prisma.bot.findUnique({where:{id},include:{runtime:true}});if(!bot)throw new NotFoundException('Bot não encontrado');if(bot.status!=='STOPPED')throw new ConflictException('Pare o bot antes de migrá-lo');const node=await this.prisma.executionNode.findUnique({where:{id:input.nodeId}});if(!node||node.status!=='ONLINE')throw new BadRequestException('O servidor de destino precisa estar online');const image=`${bot.runtime.imageRepository}:${bot.runtime.imageTag}`;if(!Array.isArray(node.runtimeImages)||!node.runtimeImages.includes(image))throw new BadRequestException(`O servidor de destino não possui o runtime ${image}`);return this.prisma.bot.update({where:{id},data:{nodeId:node.id},include:{node:true}})}
  private monthStart(){const now=new Date();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1))}
  private serializeLimit(limit:any){return{...limit,diskMb:String(limit?.diskMb??1024),bandwidthIngressMb:String(limit?.bandwidthIngressMb??10240),bandwidthEgressMb:String(limit?.bandwidthEgressMb??10240)}}
  private async defaultLimit(){return this.prisma.resourceLimit.findFirst({where:{scope:'PLAN',plan:{isDefault:true,enabled:true}}})}
  private validateLimitInput(input:UserLimitsDto){if(input.cpuMillicores>input.totalCpuMillicores)throw new BadRequestException('CPU máxima por bot não pode superar a CPU total');if(input.memoryMb>input.totalMemoryMb)throw new BadRequestException('RAM máxima por bot não pode superar a RAM total');if(input.memorySwapMb<input.memoryMb)throw new BadRequestException('MemorySwap precisa ser maior ou igual à RAM por bot')}
  private limitData(input:UserLimitsDto,owner:any){return{...owner,maxBots:input.maxBots,cpuMillicores:input.cpuMillicores,totalCpuMillicores:input.totalCpuMillicores,maxCpuPerBotMillicores:input.cpuMillicores,memoryMb:input.memoryMb,totalMemoryMb:input.totalMemoryMb,maxMemoryPerBotMb:input.memoryMb,memorySwapMb:input.memorySwapMb,diskMb:BigInt(input.diskMb),bandwidthIngressMb:BigInt(input.bandwidthIngressMb),bandwidthEgressMb:BigInt(input.bandwidthEgressMb),networkRateKbps:input.networkRateKbps||null,pidsLimit:input.pidsLimit,maxUploadMb:input.maxUploadMb,sftpRateKbps:input.sftpRateKbps||null,restartPolicy:input.restartPolicy,maxRestartCount:input.maxRestartCount,crashLoopWindowSeconds:input.crashLoopWindowSeconds,suspendOnTrafficLimit:input.suspendOnTrafficLimit,pauseOnCriticalUsage:input.pauseOnCriticalUsage}}
  private async assertUserReservations(userId:string,input:UserLimitsDto){const limits=await this.prisma.resourceLimit.findMany({where:{scope:'BOT',bot:{userId}},select:{cpuMillicores:true,memoryMb:true,diskMb:true}});const cpu=limits.reduce((n,x)=>n+x.cpuMillicores,0),memory=limits.reduce((n,x)=>n+x.memoryMb,0),disk=limits.reduce((n,x)=>n+Number(x.diskMb),0);if(cpu>input.totalCpuMillicores||memory>input.totalMemoryMb||disk>input.diskMb)throw new ConflictException(`As reservas atuais (${cpu}m CPU, ${memory} MB RAM, ${disk} MB disco) excedem a nova cota`)}
}
