import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { builtinModules } from 'module';
import { posix } from 'path';
import { unzipSync } from 'fflate';
import { PrismaService } from '../prisma/prisma.service';
import { BotFileDto, CreateBotDto, CreateEntryDto, DeleteEntriesDto, ExtractArchiveDto, MoveEntriesDto, RenameEntryDto, UpdateBotLimitsDto, UpdateStartupDto } from './bots.dto';

@Injectable()
export class BotsService {
  constructor(private readonly prisma: PrismaService) {}
  async availableRuntimes(){
    const nodes=await this.prisma.executionNode.findMany({where:{status:'ONLINE'},select:{runtimeImages:true,lastHeartbeatAt:true}});
    const counts=new Map<string,number>();
    for(const node of nodes.filter(node=>node.lastHeartbeatAt&&Date.now()-node.lastHeartbeatAt.getTime()<90000))for(const image of this.nodeImages(node.runtimeImages))counts.set(image,(counts.get(image)||0)+1);
    return [...counts].map(([image,onlineNodes])=>{const [repository,tag]=image.split(':');const dash=tag.lastIndexOf('-');const version=dash<0?tag:tag.slice(0,dash);const variant=(dash<0?'ALPINE':tag.slice(dash+1).toUpperCase());return{image,language:repository==='node'?'NODEJS':'PYTHON',label:repository==='node'?'Node.js':'Python',version,variant,onlineNodes}}).sort((a,b)=>a.language.localeCompare(b.language)||b.version.localeCompare(a.version));
  }
  list(userId: string) {
    return this.prisma.bot.findMany({ where: { userId }, include: { runtime: true, node: { select: { id: true, name: true, status: true } } }, orderBy: { createdAt: 'desc' } });
  }
  async get(userId: string, id: string) {
    const admin=await this.isAdmin(userId);const bot = await this.prisma.bot.findFirst({ where: { id,...(admin?{}:{userId}) }, include: { runtime: true, node: {select:{id:true,name:true,status:true,agentVersion:true}}, limits:{where:{scope:'BOT'},take:1}, user:{select:{limits:{where:{scope:'USER'},take:1},plan:{select:{limits:{where:{scope:'PLAN'},take:1}}}}} } });
    if (!bot) throw new NotFoundException('Bot não encontrado');
    const plan=bot.user.limits[0]||bot.user.plan?.limits[0]||await this.defaultLimit(),limit=bot.limits[0]||plan;const {limits,user,...safe}=bot;
    return {...safe,effectiveLimits:{cpuMillicores:limit?.cpuMillicores??250,memoryMb:limit?.memoryMb??256,diskMb:Number(limit?.diskMb??BigInt(1024))},planLimits:{cpuMillicores:plan?.cpuMillicores??250,memoryMb:plan?.memoryMb??256,diskMb:Number(plan?.diskMb??BigInt(1024))}};
  }
  async updateLimits(userId:string,id:string,input:UpdateBotLimitsDto){
    const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,userId:true}});if(!bot)throw new NotFoundException('Bot não encontrado');
    const owner=await this.prisma.user.findUnique({where:{id:bot.userId},include:{limits:{where:{scope:'USER'},take:1},plan:{include:{limits:{where:{scope:'PLAN'},take:1}}}}});const ownerLimit=owner?.limits[0]||owner?.plan?.limits[0]||await this.prisma.resourceLimit.findFirst({where:{scope:'PLAN',plan:{isDefault:true,enabled:true}}});const ceiling={cpuMillicores:ownerLimit?.cpuMillicores??250,memoryMb:ownerLimit?.memoryMb??256,diskMb:Number(ownerLimit?.diskMb??BigInt(1024))};
    if(input.cpuMillicores>ceiling.cpuMillicores||input.memoryMb>ceiling.memoryMb||input.diskMb>ceiling.diskMb)throw new BadRequestException(`Limite máximo do plano: ${ceiling.cpuMillicores}m CPU, ${ceiling.memoryMb} MB RAM e ${ceiling.diskMb} MB disco`);
    const reserved=await this.prisma.resourceLimit.aggregate({where:{scope:'BOT',bot:{userId:bot.userId,id:{not:id}}},_sum:{cpuMillicores:true,memoryMb:true,diskMb:true}});if((reserved._sum.cpuMillicores||0)+input.cpuMillicores>(ownerLimit?.totalCpuMillicores??ceiling.cpuMillicores)||(reserved._sum.memoryMb||0)+input.memoryMb>(ownerLimit?.totalMemoryMb??ceiling.memoryMb)||Number(reserved._sum.diskMb||0n)+input.diskMb>ceiling.diskMb)throw new BadRequestException('A soma das reservas dos bots ultrapassa a cota total do usuário');
    const data={scope:'BOT' as const,userId:null,botId:id,maxBots:null,cpuMillicores:input.cpuMillicores,memoryMb:input.memoryMb,memorySwapMb:Math.max(input.memoryMb,ownerLimit?.memorySwapMb??input.memoryMb),diskMb:BigInt(input.diskMb),bandwidthIngressMb:ownerLimit?.bandwidthIngressMb??BigInt(10240),bandwidthEgressMb:ownerLimit?.bandwidthEgressMb??BigInt(10240),networkRateKbps:ownerLimit?.networkRateKbps??null,pidsLimit:ownerLimit?.pidsLimit??100,maxUploadMb:ownerLimit?.maxUploadMb??100,sftpRateKbps:ownerLimit?.sftpRateKbps??null,restartPolicy:ownerLimit?.restartPolicy??'ON_FAILURE',maxRestartCount:ownerLimit?.maxRestartCount??5,crashLoopWindowSeconds:ownerLimit?.crashLoopWindowSeconds??300,suspendOnTrafficLimit:ownerLimit?.suspendOnTrafficLimit??true,pauseOnCriticalUsage:ownerLimit?.pauseOnCriticalUsage??false};
    const existing=await this.prisma.resourceLimit.findFirst({where:{scope:'BOT',botId:id},select:{id:true}});if(existing)await this.prisma.resourceLimit.update({where:{id:existing.id},data});else await this.prisma.resourceLimit.create({data});
    return{success:true,effectiveLimits:input};
  }
  async create(userId: string, input: CreateBotDto) {
    const [owner,currentBots]=await Promise.all([this.prisma.user.findUnique({where:{id:userId},include:{limits:{where:{scope:'USER'},take:1},plan:{include:{limits:{where:{scope:'PLAN'},take:1}}}}}),this.prisma.bot.count({where:{userId}})]);const limit=owner?.limits[0]||owner?.plan?.limits[0]||await this.prisma.resourceLimit.findFirst({where:{scope:'PLAN',plan:{isDefault:true,enabled:true}}});
    const maxBots=limit?.maxBots??5;
    if(currentBots>=maxBots)throw new BadRequestException(`Você atingiu o limite de ${maxBots} bot(s)`);
    const image=`${input.language==='NODEJS'?'node':'python'}:${input.version}-${input.variant.toLowerCase()}`;
    const nodes=await this.prisma.executionNode.findMany({
      where:{status:'ONLINE'},
      include:{
        bots:{
          select:{
            limits:{where:{scope:'BOT'},take:1},
            user:{
              select:{
                limits:{where:{scope:'USER'},take:1},
                plan:{select:{limits:{where:{scope:'PLAN'},take:1}}},
              },
            },
          },
        },
        _count:{select:{bots:true}},
      },
    });
    const requested={cpu:limit?.cpuMillicores??250,memory:limit?.memoryMb??256,disk:Number(limit?.diskMb??1024n)};
    const compatible=nodes.filter(node=>{
      if(!node.lastHeartbeatAt||Date.now()-node.lastHeartbeatAt.getTime()>=90000||!this.nodeImages(node.runtimeImages).includes(image))return false;
      const reserved=node.bots.reduce((sum,b)=>{const l=b.limits[0]||b.user.limits[0]||b.user.plan?.limits[0];return{cpu:sum.cpu+(l?.cpuMillicores??250),memory:sum.memory+(l?.memoryMb??256),disk:sum.disk+Number(l?.diskMb??1024n)}},{cpu:0,memory:0,disk:0});
      return reserved.cpu+requested.cpu<=node.totalCpuMillicores&&reserved.memory+requested.memory<=node.totalMemoryMb&&reserved.disk+requested.disk<=Number(node.totalDiskMb);
    }).sort((a,b)=>a._count.bots-b._count.bots);
    if(!compatible.length)throw new BadRequestException('Nenhum Runner online possui este runtime. Atualize ou prepare uma VPS primeiro.');
    const slugBase = input.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'bot';
    const slug = `${slugBase}-${Math.random().toString(36).slice(2, 7)}`;
    const runtime = await this.prisma.runtime.upsert({
      where: { language_version_variant: { language: input.language, version: input.version, variant: input.variant } },
      update: {},
      create: {
        language: input.language, version: input.version, variant: input.variant,
        imageRepository: input.language === 'NODEJS' ? 'node' : 'python', imageTag: `${input.version}-${input.variant.toLowerCase()}`,
        imageDigest: 'pending-verification', installCommand: input.language === 'NODEJS' ? ['npm', 'ci'] : ['pip', 'install', '-r', 'requirements.txt'],
        defaultStartCommand: input.language === 'NODEJS' ? ['node'] : ['python'],
      },
    });
    const node=compatible[0];
    return this.prisma.bot.create({ data: {
      userId, runtimeId: runtime.id, nodeId:node?.id, name: input.name.trim(), slug, entrypoint: input.entrypoint,
      startCommand: input.language === 'NODEJS' ? ['node', input.entrypoint] : ['python', input.entrypoint],
    }, include: { runtime: true } });
  }
  async deleteBot(userId:string,id:string){
    const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,nodeId:true,node:{select:{status:true}}}});
    if(!bot)throw new NotFoundException('Bot não encontrado');
    if(bot.nodeId&&bot.node?.status==='ONLINE'){const active=await this.prisma.agentJob.count({where:{botId:id,status:{in:['QUEUED','RUNNING']}}});if(active)throw new BadRequestException('Aguarde a tarefa atual terminar antes de excluir');await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'DELETE'}});await this.prisma.bot.update({where:{id},data:{status:'STOPPING'}});return{success:true,queued:true}}
    await this.prisma.bot.delete({where:{id}});return{success:true,queued:false}
  }
  async files(userId:string,id:string){await this.ownedBot(userId,id);const files=await this.prisma.botFile.findMany({where:{botId:id,NOT:{path:{endsWith:'.env'}}},select:{id:true,path:true,byteSize:true,updatedAt:true},orderBy:{path:'asc'}});return files.map(file=>file.path.endsWith('/.beako-dir')?{...file,path:file.path.slice(0,-11),isDirectory:true}:{...file,isDirectory:false})}
  async uploadFile(userId:string,id:string,input:BotFileDto){
    await this.ownedBot(userId,id);
    this.rejectEnvPath(input.path);
    const content=Buffer.from(input.contentBase64,'base64');
    const limit=await this.effectiveLimitForBot(id);
    const maxUpload=(limit?.maxUploadMb??100)*1024*1024;
    if(content.length>maxUpload)throw new BadRequestException(`Arquivo maior que o limite de ${limit?.maxUploadMb??100} MB`);
    const current=await this.prisma.botFile.aggregate({where:{botId:id,path:{not:input.path}},_sum:{byteSize:true}});
    const diskLimit=Number(limit?.diskMb??BigInt(1024))*1024*1024;
    if((current._sum.byteSize??0)+content.length>diskLimit)throw new BadRequestException('O bot atingiu o limite de armazenamento');
    const file=await this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:input.path}},update:{content,byteSize:content.length},create:{botId:id,path:input.path,content,byteSize:content.length},select:{id:true,path:true,byteSize:true,updatedAt:true}});
    await this.queueSync(id);
    return file;
  }
  async uploadFiles(userId:string,id:string,inputs:BotFileDto[]){await this.ownedBot(userId,id);const paths=inputs.map(input=>this.safePath(input.path));if(new Set(paths).size!==paths.length)throw new BadRequestException('O lote contém arquivos com o mesmo caminho');const decoded=inputs.map((input,index)=>({path:paths[index],content:Buffer.from(input.contentBase64,'base64')}));const limit=await this.effectiveLimitForBot(id);const maxUpload=(limit?.maxUploadMb??100)*1024*1024;for(const file of decoded)if(file.content.length>maxUpload)throw new BadRequestException(`O arquivo ${file.path} ultrapassa o limite de ${limit?.maxUploadMb??100} MB`);const current=await this.prisma.botFile.aggregate({where:{botId:id,path:{notIn:paths}},_sum:{byteSize:true}});const incoming=decoded.reduce((total,file)=>total+file.content.length,0),diskLimit=Number(limit?.diskMb??BigInt(1024))*1024*1024;if((current._sum.byteSize??0)+incoming>diskLimit)throw new BadRequestException('O lote ultrapassa o limite de armazenamento do bot');await this.prisma.$transaction(decoded.map(file=>this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:file.path}},update:{content:file.content,byteSize:file.content.length},create:{botId:id,path:file.path,content:file.content,byteSize:file.content.length}})));await this.queueSync(id);return{success:true,uploaded:decoded.length,totalBytes:incoming}}
  async removeFile(userId:string,id:string,path:string){await this.ownedBot(userId,id);const safe=this.safePath(path);await this.prisma.botFile.deleteMany({where:{botId:id,OR:[{path:safe},{path:safe+'/.beako-dir'},{path:{startsWith:safe+'/'}}]}});await this.queueSync(id);return{success:true}}
  async fileContent(userId:string,id:string,path:string){await this.ownedBot(userId,id);const safe=this.safePath(path);const file=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:safe}}});if(!file)throw new NotFoundException('Arquivo não encontrado');if(file.byteSize>2*1024*1024)throw new BadRequestException('Arquivos acima de 2 MB não podem ser editados no navegador');const content=Buffer.from(file.content);if(content.includes(0))throw new BadRequestException('Arquivo binário não pode ser editado');return{path:safe,content:content.toString('utf8'),byteSize:file.byteSize,updatedAt:file.updatedAt}}
  async downloadFile(userId:string,id:string,path:string){await this.ownedBot(userId,id);const safe=this.safePath(path);const file=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:safe}},select:{path:true,content:true,byteSize:true,updatedAt:true}});if(!file)throw new NotFoundException('Arquivo não encontrado');return{path:safe,contentBase64:Buffer.from(file.content).toString('base64'),byteSize:file.byteSize,updatedAt:file.updatedAt}}
  async createEntry(userId:string,id:string,input:CreateEntryDto){await this.ownedBot(userId,id);const path=this.safePath(input.path).replace(/\/$/,'');const stored=input.type==='DIRECTORY'?path+'/.beako-dir':path;const exists=await this.prisma.botFile.count({where:{botId:id,path:stored}});if(exists)throw new BadRequestException('Já existe um item com este nome');await this.prisma.botFile.create({data:{botId:id,path:stored,content:Buffer.alloc(0),byteSize:0}});await this.queueSync(id);return{success:true,path,type:input.type}}
  async renameEntry(userId:string,id:string,input:RenameEntryDto){await this.ownedBot(userId,id);const from=this.safePath(input.from).replace(/\/$/,'');const to=this.safePath(input.to).replace(/\/$/,'');if(from===to)return{success:true};const sources=await this.prisma.botFile.findMany({where:{botId:id,OR:[{path:from},{path:from+'/.beako-dir'},{path:{startsWith:from+'/'}}]}});if(!sources.length)throw new NotFoundException('Arquivo ou pasta não encontrado');const changes=sources.map(file=>({file,path:file.path===from?to:file.path===from+'/.beako-dir'?to+'/.beako-dir':to+file.path.slice(from.length)}));for(const change of changes)if(await this.prisma.botFile.count({where:{botId:id,path:change.path,id:{not:change.file.id}}}))throw new BadRequestException('O destino já contém um item com o mesmo nome');await this.prisma.$transaction(changes.map(change=>this.prisma.botFile.update({where:{id:change.file.id},data:{path:change.path}})));await this.queueSync(id);return{success:true}}
  async moveEntries(userId:string,id:string,input:MoveEntriesDto){
    await this.ownedBot(userId,id);const destination=input.destination?this.safePath(input.destination).replace(/\/$/,''):'';const roots=[...new Set(input.paths.map(value=>this.safePath(value).replace(/\/$/,'')))].filter(root=>!input.paths.some(other=>other!==root&&root.startsWith(other.replace(/\/$/,'')+'/')));
    for(const root of roots)if(destination===root||destination.startsWith(root+'/'))throw new BadRequestException('Uma pasta não pode ser movida para dentro dela mesma');
    const all=await this.prisma.botFile.findMany({where:{botId:id}});const sourceIds=new Set<string>();const changes:{id:string;path:string}[]=[];
    for(const root of roots){const source=all.filter(file=>file.path===root||file.path===root+'/.beako-dir'||file.path.startsWith(root+'/'));if(!source.length)throw new NotFoundException(`Item não encontrado: ${root}`);const targetRoot=[destination,posix.basename(root)].filter(Boolean).join('/');for(const file of source){sourceIds.add(file.id);changes.push({id:file.id,path:file.path===root?targetRoot:file.path===root+'/.beako-dir'?targetRoot+'/.beako-dir':targetRoot+file.path.slice(root.length)})}}
    if(new Set(changes.map(change=>change.path)).size!==changes.length)throw new BadRequestException('A seleção contém nomes duplicados no destino');const occupied=new Set(all.filter(file=>!sourceIds.has(file.id)).map(file=>file.path));if(changes.some(change=>occupied.has(change.path)))throw new BadRequestException('O destino já contém um item com o mesmo nome');
    await this.prisma.$transaction(changes.map(change=>this.prisma.botFile.update({where:{id:change.id},data:{path:change.path}})));await this.queueSync(id);return{success:true,moved:roots.length};
  }
  async updateStartup(userId:string,id:string,input:UpdateStartupDto){const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,runtime:{select:{language:true}}}});if(!bot)throw new NotFoundException('Bot não encontrado');const entrypoint=this.safePath(input.entrypoint);const exists=await this.prisma.botFile.count({where:{botId:id,path:entrypoint}});if(!exists)throw new BadRequestException('O arquivo inicial informado não existe');const command=bot.runtime.language==='NODEJS'?'node':'python';const updated=await this.prisma.bot.update({where:{id},data:{entrypoint,startCommand:[command,entrypoint]},select:{entrypoint:true,startCommand:true}});await this.queueSync(id);return{success:true,...updated}}
  async deleteEntries(userId:string,id:string,input:DeleteEntriesDto){await this.ownedBot(userId,id);const roots=[...new Set(input.paths.map(value=>this.safePath(value).replace(/\/$/,'')))];await this.prisma.botFile.deleteMany({where:{botId:id,OR:roots.flatMap(path=>[{path},{path:path+'/.beako-dir'},{path:{startsWith:path+'/'}}])}});await this.queueSync(id);return{success:true,deleted:roots.length}}
  async extractArchive(userId:string,id:string,input:ExtractArchiveDto){await this.ownedBot(userId,id);const archivePath=this.safePath(input.path);if(!archivePath.toLowerCase().endsWith('.zip'))throw new BadRequestException('Selecione um arquivo .zip');const archive=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:archivePath}}});if(!archive)throw new NotFoundException('ZIP não encontrado');const limit=await this.effectiveLimitForBot(id);const current=await this.prisma.botFile.aggregate({where:{botId:id,id:{not:archive.id}},_sum:{byteSize:true}});const maxBytes=Math.max(0,Number(limit?.diskMb??BigInt(1024))*1024*1024-(current._sum.byteSize??0));let expected=0;let extracted:Record<string,Uint8Array>;try{extracted=unzipSync(new Uint8Array(archive.content),{filter:file=>{expected+=file.originalSize;if(expected>maxBytes)throw new Error('limit');return true}})}catch{throw new BadRequestException('ZIP inválido ou maior que o espaço disponível')};const destination=input.destination?this.safePath(input.destination).replace(/\/$/,''):posix.dirname(archivePath)==='.'?'':posix.dirname(archivePath);const entries=Object.entries(extracted).filter(([raw])=>!raw.endsWith('/')).map(([raw,data])=>({target:this.safePath([destination,this.safePath(raw)].filter(Boolean).join('/')),content:Buffer.from(data)}));await this.prisma.$transaction(entries.map(file=>this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:file.target}},update:{content:file.content,byteSize:file.content.length},create:{botId:id,path:file.target,content:file.content,byteSize:file.content.length}})));if(input.deleteArchive)await this.prisma.botFile.delete({where:{id:archive.id}});await this.queueSync(id);return{success:true,filesExtracted:entries.length}}
  async action(userId:string,id:string,action:string){if(action==='START'||action==='RESTART')return this.autoDeploy(userId,id);const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,nodeId:true,node:{select:{status:true}}}});if(!bot)throw new NotFoundException('Bot não encontrado');if(!bot.nodeId||bot.node?.status!=='ONLINE')throw new BadRequestException('Atribua um Runner online a este bot');const active=await this.prisma.agentJob.findFirst({where:{botId:id,status:{in:['QUEUED','RUNNING']}}});if(active)throw new BadRequestException('Já existe uma tarefa em andamento para este bot');if(action==='INSTALL')await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'SYNC'}});const job=await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action}});if(action==='STOP')await this.prisma.bot.update({where:{id},data:{status:'STOPPING'}});return job}
  async jobs(userId:string,id:string){await this.ownedBot(userId,id);return this.prisma.agentJob.findMany({where:{botId:id},select:{id:true,action:true,status:true,output:true,error:true,createdAt:true,startedAt:true,finishedAt:true},orderBy:{createdAt:'desc'},take:20})}
  async dependencies(userId:string,id:string){
    await this.ownedBot(userId,id);const bot=await this.prisma.bot.findUnique({where:{id},select:{runtime:{select:{language:true}}}});
    const files=await this.prisma.botFile.findMany({where:{botId:id},select:{path:true,content:true}});
    if(bot?.runtime.language==='PYTHON'){
      const imports=new Set<string>();const pattern=/^(?:from|import)\s+([a-zA-Z0-9_]+)/gm;for(const file of files.filter(file=>/\.py$/.test(file.path))){const source=Buffer.from(file.content).toString('utf8');let match:RegExpExecArray|null;while((match=pattern.exec(source)))imports.add(match[1])}
      const mapping:Record<string,string>={telegram:'python-telegram-bot',PIL:'Pillow',discord:'discord.py',dotenv:'python-dotenv',yaml:'PyYAML',bs4:'beautifulsoup4',cv2:'opencv-python',Crypto:'pycryptodome',sklearn:'scikit-learn',dateutil:'python-dateutil',requests:'requests',httpx:'httpx',aiohttp:'aiohttp',flask:'flask',fastapi:'fastapi',numpy:'numpy',pandas:'pandas',pyrogram:'pyrogram',telethon:'telethon'};const detected=[...imports].flatMap(name=>mapping[name]?[mapping[name]]:[]).sort();const manifest=files.find(file=>file.path==='requirements.txt');const declared=manifest?this.sanitizePythonRequirements(Buffer.from(manifest.content).toString('utf8').split(/\r?\n/).map(line=>line.trim()).filter(Boolean)).filter(line=>!line.startsWith('#')).map(line=>line.split(/[<>=!~\[]/)[0].trim()):[];const catalog=['python-telegram-bot','discord.py','Pillow','requests','httpx','aiohttp','python-dotenv','PyYAML','beautifulsoup4','flask','fastapi','numpy','pandas','opencv-python','pyrogram','telethon'];return{language:'PYTHON',detected,declared,missing:detected.filter(name=>!declared.some(item=>item.toLowerCase()===name.toLowerCase())),hasPackageJson:Boolean(manifest),catalog:[...new Set([...detected,...catalog])]};
    }
    const detected=new Set<string>();const builtins=new Set([...builtinModules,...builtinModules.map(name=>'node:'+name)]);
    const pattern=/(?:require\s*\(\s*|from\s+|import\s*\(\s*|import\s+)["']([^"']+)["']/g;
    for(const file of files.filter(file=>/\.(?:js|cjs|mjs|ts|tsx|jsx)$/.test(file.path))){const source=Buffer.from(file.content).toString('utf8');let match:RegExpExecArray|null;while((match=pattern.exec(source))){const spec=match[1];if(spec.startsWith('.')||spec.startsWith('/')||builtins.has(spec))continue;detected.add(spec.startsWith('@')?spec.split('/').slice(0,2).join('/'):spec.split('/')[0])}}
    let declared:Record<string,string>={};const manifest=files.find(file=>file.path==='package.json');if(manifest)try{const parsed=JSON.parse(Buffer.from(manifest.content).toString('utf8'));declared={...(parsed.dependencies||{}),...(parsed.devDependencies||{})}}catch{}
    const all=[...detected].sort();return{language:'NODEJS',detected:all,declared:Object.keys(declared).sort(),missing:all.filter(name=>!declared[name]),hasPackageJson:Boolean(manifest),catalog:all};
  }
  async installDependencies(userId:string,id:string,packages:string[]){
    const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,nodeId:true,entrypoint:true,runtime:{select:{language:true}}}});if(!bot)throw new NotFoundException('Bot não encontrado');if(!bot.nodeId)throw new BadRequestException('Bot sem Runner atribuído');
    if(bot.runtime.language==='PYTHON'){const existing=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:'requirements.txt'}}});const lines=this.sanitizePythonRequirements(existing?Buffer.from(existing.content).toString('utf8').split(/\r?\n/).map(line=>line.trim()).filter(Boolean):[]);const declared=new Set(lines.map(line=>line.split(/[<>=!~\[]/)[0].toLowerCase()));for(const name of [...new Set(packages)])if(!declared.has(name.toLowerCase()))lines.push(name);const content=Buffer.from(lines.join('\n')+'\n');await this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:'requirements.txt'}},update:{content,byteSize:content.length},create:{botId:id,path:'requirements.txt',content,byteSize:content.length}});const syncActive=await this.prisma.agentJob.count({where:{botId:id,action:'SYNC',status:{in:['QUEUED','RUNNING']}}});if(!syncActive)await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'SYNC'}});const installActive=await this.prisma.agentJob.count({where:{botId:id,action:'INSTALL',status:{in:['QUEUED','RUNNING']}}});if(!installActive)await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'INSTALL'}});return{success:true,requirements:lines}}
    const existing=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:'package.json'}}});let manifest:any={name:'beakohost-bot',version:'1.0.0',private:true,main:bot.entrypoint};if(existing)try{manifest=JSON.parse(Buffer.from(existing.content).toString('utf8'))}catch{throw new BadRequestException('package.json inválido')};manifest.dependencies={...(manifest.dependencies||{})};for(const name of [...new Set(packages)])manifest.dependencies[name]=this.compatibleDependency(name)||manifest.dependencies[name]||'latest';for(const name of Object.keys(manifest.dependencies)){const version=this.compatibleDependency(name);if(version)manifest.dependencies[name]=version}const content=Buffer.from(JSON.stringify(manifest,null,2)+'\n');await this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:'package.json'}},update:{content,byteSize:content.length},create:{botId:id,path:'package.json',content,byteSize:content.length}});
    const syncActive=await this.prisma.agentJob.count({where:{botId:id,action:'SYNC',status:{in:['QUEUED','RUNNING']}}});if(!syncActive)await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'SYNC'}});const installActive=await this.prisma.agentJob.count({where:{botId:id,action:'INSTALL',status:{in:['QUEUED','RUNNING']}}});if(!installActive)await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'INSTALL'}});return{success:true,packageJson:manifest};
  }
  async autoDeploy(userId:string,id:string){
    const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true,nodeId:true,entrypoint:true,runtime:{select:{language:true}}}});if(!bot)throw new NotFoundException('Bot não encontrado');if(!bot.nodeId)throw new BadRequestException('Aguardando um Runner compatível');
    if(bot.runtime.language==='NODEJS'){
      const info=await this.dependencies(userId,id);const existing=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:'package.json'}}});let manifest:any={name:'beakohost-bot',version:'1.0.0',private:true,main:bot.entrypoint,scripts:{start:`node ${bot.entrypoint}`}};if(existing)try{manifest=JSON.parse(Buffer.from(existing.content).toString('utf8'))}catch{throw new BadRequestException('package.json inválido')};manifest.dependencies={...(manifest.dependencies||{})};for(const name of info.missing)manifest.dependencies[name]=this.compatibleDependency(name)||'latest';for(const name of Object.keys(manifest.dependencies)){const version=this.compatibleDependency(name);if(version)manifest.dependencies[name]=version}const content=Buffer.from(JSON.stringify(manifest,null,2)+'\n');await this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:'package.json'}},update:{content,byteSize:content.length},create:{botId:id,path:'package.json',content,byteSize:content.length}});
    }else{
      const info=await this.dependencies(userId,id);const existing=await this.prisma.botFile.findUnique({where:{botId_path:{botId:id,path:'requirements.txt'}}});const lines=this.sanitizePythonRequirements(existing?Buffer.from(existing.content).toString('utf8').split(/\r?\n/).map(line=>line.trim()).filter(Boolean):[]);const declared=new Set(lines.filter(line=>!line.startsWith('#')).map(line=>line.split(/[<>=!~\[]/)[0].toLowerCase()));for(const name of info.missing)if(!declared.has(name.toLowerCase()))lines.push(name);const content=Buffer.from(lines.join('\n')+'\n');await this.prisma.botFile.upsert({where:{botId_path:{botId:id,path:'requirements.txt'}},update:{content,byteSize:content.length},create:{botId:id,path:'requirements.txt',content,byteSize:content.length}});
    }
    const existingDeploy=await this.prisma.agentJob.findFirst({where:{botId:id,action:'DEPLOY',status:{in:['QUEUED','RUNNING']}}});if(existingDeploy)return{success:true,queued:true,jobId:existingDeploy.id};
    const job=await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'DEPLOY'}});await this.prisma.bot.update({where:{id},data:{status:'STARTING'}});return{success:true,queued:true,jobId:job.id};
  }
  async logs(userId:string,id:string){await this.ownedBot(userId,id);const chunks=await this.prisma.botLogChunk.findMany({where:{botId:id},orderBy:{lastTimestamp:'desc'},take:1});return{content:chunks[0]?.content||'',updatedAt:chunks[0]?.lastTimestamp||null}}
  private async queueSync(id:string){const bot=await this.prisma.bot.findUnique({where:{id},select:{nodeId:true}});if(!bot?.nodeId)return;const active=await this.prisma.agentJob.count({where:{botId:id,action:'SYNC',status:{in:['QUEUED','RUNNING']}}});if(!active)await this.prisma.agentJob.create({data:{nodeId:bot.nodeId,botId:id,action:'SYNC'}})}
  private async ownedBot(userId:string,id:string){const admin=await this.isAdmin(userId);const bot=await this.prisma.bot.findFirst({where:{id,...(admin?{}:{userId})},select:{id:true}});if(!bot)throw new NotFoundException('Bot não encontrado');return bot}
  private async isAdmin(userId:string){return Boolean(await this.prisma.user.count({where:{id:userId,role:'ADMIN',status:'ACTIVE'}}))}
  private defaultLimit(){return this.prisma.resourceLimit.findFirst({where:{scope:'PLAN',plan:{isDefault:true,enabled:true}}})}
  private async effectiveLimitForBot(botId:string){const bot=await this.prisma.bot.findUnique({where:{id:botId},select:{limits:{where:{scope:'BOT'},take:1},user:{select:{limits:{where:{scope:'USER'},take:1},plan:{select:{limits:{where:{scope:'PLAN'},take:1}}}}}});return bot?.limits[0]||bot?.user.limits[0]||bot?.user.plan?.limits[0]||await this.defaultLimit()}
  private nodeImages(value:unknown){return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'&&/^(node|python):[a-zA-Z0-9.-]+$/.test(item)):[]}
  private compatibleDependency(name:string){const versions:Record<string,string>={'node-telegram-bot-api':'0.66.0'};return versions[name]||null}
  private sanitizePythonRequirements(lines:string[]){const standard=new Set(['abc','argparse','asyncio','base64','collections','concurrent','contextlib','csv','dataclasses','datetime','decimal','email','enum','functools','glob','hashlib','heapq','html','http','importlib','inspect','io','itertools','json','logging','math','multiprocessing','operator','os','pathlib','pickle','platform','queue','random','re','secrets','shutil','signal','socket','sqlite3','statistics','string','struct','subprocess','sys','tempfile','threading','time','traceback','types','typing','unittest','urllib','uuid','warnings','weakref','xml','zipfile']);return lines.filter(line=>line.startsWith('#')||!standard.has(line.split(/[<>=!~\[]/)[0].trim().toLowerCase()))}
  private safePath(value:string){const normalized=posix.normalize(String(value||'').replace(/\\/g,'/')).replace(/^\.\//,'');if(!normalized||normalized==='.'||normalized.startsWith('/')||normalized==='..'||normalized.startsWith('../')||normalized.includes('/../')||normalized.length>240||!/^[a-zA-Z0-9_./@()+ -]+$/.test(normalized))throw new BadRequestException('Caminho inválido');this.rejectEnvPath(normalized);return normalized}
  private rejectEnvPath(path:string){if(path.split('/').includes('.env'))throw new BadRequestException('Use a aba Variáveis para configurar segredos; arquivos .env não são permitidos')}
}
